/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interpret Text */
        post: operations["interpret_text_api_v1_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Part */
        post: operations["generate_part_api_v1_parts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CadPart */
        CadPart: {
            /**
             * Shape
             * @default box
             * @constant
             */
            shape: "box";
            dimensions: components["schemas"]["Dimensions"];
            /** Holes */
            holes?: components["schemas"]["Hole"][];
            /** Fillets */
            fillets?: components["schemas"]["Fillet"][];
            /**
             * Material
             * @default aluminum
             */
            material: string | null;
        };
        /** DimensionIntent */
        DimensionIntent: {
            /** Length */
            length?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
        };
        /** Dimensions */
        Dimensions: {
            /**
             * Length
             * @description Length in mm
             */
            length: number;
            /**
             * Width
             * @description Width in mm
             */
            width: number;
            /**
             * Height
             * @description Height in mm
             */
            height: number;
        };
        /** Fillet */
        Fillet: {
            /**
             * Radius
             * @description Fillet radius in mm
             */
            radius: number;
            /**
             * Edges
             * @default all
             * @enum {string}
             */
            edges: "all" | "top" | "bottom";
        };
        /** FilletIntent */
        FilletIntent: {
            /** Radius */
            radius?: number | null;
            /** Location */
            location?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hole */
        Hole: {
            /**
             * Diameter
             * @description Hole diameter in mm
             */
            diameter: number;
            /**
             * Depth
             * @description Hole depth in mm
             */
            depth: number;
            /** @description Hole position */
            position?: components["schemas"]["Position"];
        };
        /** HoleIntent */
        HoleIntent: {
            /** Diameter */
            diameter?: number | null;
            /** Depth */
            depth?: number | null;
            /** Location */
            location?: string | null;
        };
        /** InterpretRequest */
        InterpretRequest: {
            /**
             * Text
             * @description Natural language description of the part
             */
            text: string;
        };
        /** InterpretResponse */
        InterpretResponse: {
            intent: components["schemas"]["PartIntent"];
        };
        /** PartGenerationResult */
        PartGenerationResult: {
            /** Step File Path */
            step_file_path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /** Message */
            message?: string | null;
        };
        /** PartIntent */
        PartIntent: {
            /** Shape */
            shape?: "box" | null;
            dimensions?: components["schemas"]["DimensionIntent"] | null;
            /** Holes */
            holes?: components["schemas"]["HoleIntent"][];
            /** Fillets */
            fillets?: components["schemas"]["FilletIntent"][];
            /** Material */
            material?: string | null;
            /** Missing Information */
            missing_information?: string[];
        };
        /** Position */
        Position: {
            /**
             * X
             * @description X coordinate in mm
             * @default 0
             */
            x: number;
            /**
             * Y
             * @description Y coordinate in mm
             * @default 0
             */
            y: number;
            /**
             * Z
             * @description Z coordinate in mm
             * @default 0
             */
            z: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    interpret_text_api_v1_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_part_api_v1_parts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadPart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartGenerationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
